plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group
base { archivesName = 'alchemical-bags-fabric-26.2' }

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    implementation files("../../HeiShan/26.2整合包/.minecraft/versions/26.2-Fabric/mods/huge-storage-90-1.1.4.jar")
    implementation files("../../HeiShan/26.2整合包/.minecraft/versions/26.2-Fabric/mods/carpet-tis-addition-v1.82.3-mc26.2.jar")
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand 'version': project.version }
}

tasks.withType(JavaCompile).configureEach { options.release = 25 }
java { sourceCompatibility = JavaVersion.VERSION_25; targetCompatibility = JavaVersion.VERSION_25 }
